name: light_control_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icon/logo.png 

  fonts:
    - family: RobotoCondensed
      fonts: 
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoCondensed-BoldItalic.ttf
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
        - asset: assets/fonts/RobotoCondensed-Regular.ttf

    - family: BebasNeue
      fonts: 
        - asset: assets/fonts/BebasNeue-Regular.ttf
          weight: 700

    - family: Merriweather
      fonts: 
        - asset: assets/fonts/Merriweather-Bold.ttf
          weight: 700
        - asset: assets/fonts/Merriweather-BoldItalic.ttf
        - asset: assets/fonts/Merriweather-Italic.ttf
        - asset: assets/fonts/Merriweather-Regular.ttf

    - family: PlayfairDisplay
      fonts: 
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayfairDisplay-BoldItalic.ttf
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf           
